### ISSUE TITLE
An error occured with jsoup Jsoup. App gets crashed while fetching meta data

### ISSUE THREAD

**Issue by BharathirajaPerumal** [LeonardoCardoso/Android-Link-Preview#13]
Find the log exception details below:

E/UncaughtException: java.lang.RuntimeException: An error occured while executing doInBackground()
                                                                      at android.os.AsyncTask$3.done(AsyncTask.java:300)
                                                                      at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
                                                                      at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
                                E/UncaughtException: java.lang.RuntimeException: An error occured while executing doInBackground()
                                                                      at android.os.AsyncTask$3.done(AsyncTask.java:300)
                                                                      at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
                                                                      at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
                                                                      at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                      at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
                                                                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                      at java.lang.Thread.run(Thread.java:841)
                                                                   Caused by: java.lang.VerifyError: org/jsoup/parser/HtmlTreeBuilderState$7
                                                                      at org.jsoup.parser.HtmlTreeBuilderState.<clinit>(HtmlTreeBuilderState.java:245)
                                                                      at org.jsoup.parser.HtmlTreeBuilder.parse(HtmlTreeBuilder.java:54)
                                                                      at org.jsoup.parser.Parser.parse(Parser.java:100)
                                                                      at org.jsoup.Jsoup.parse(Jsoup.java:58)
                                                                      at com.leocardz.link.preview.library.TextCrawler.stripTags(TextCrawler.java:261)
                                                                      at com.leocardz.link.preview.library.TextCrawler.access$700(TextCrawler.java:18)
                                                                      at com.leocardz.link.preview.library.TextCrawler$GetCode.doInBackground(TextCrawler.java:147)
                                                                      at com.leocardz.link.preview.library.TextCrawler$GetCode.doInBackground(TextCrawler.java:43)
                                                                      at android.os.AsyncTask$2.call(AsyncTask.java:288)
                                                                      at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                      at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231) 
                                                                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                      at java.lang.Thread.run(Thread.java:841)                                       at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                      at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.jaE/UncaughtException: java.lang.RuntimeException: An error occured while executing doInBackground()
                                                                      at android.os.AsyncTask$3.done(AsyncTask.java:300)
                                                                      at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
                                                                      at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
                                                                      at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                      at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
                                                                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                      at java.lang.Thread.run(Thread.java:841)
                                                                   Caused by: java.lang.VerifyError: org/jsoup/parser/HtmlTreeBuilderState$7
                                                                      at org.jsoup.parser.HtmlTreeBuilderState.<clinit>(HtmlTreeBuilderState.java:245)
                                                                      at org.jsoup.parser.HtmlTreeBuilder.parse(HtmlTreeBuilder.java:54)
                                                                      at org.jsoup.parser.Parser.parse(Parser.java:100)
                                                                      at org.jsoup.Jsoup.parse(Jsoup.java:58)
                                                                      at com.leocardz.link.preview.library.TextCrawler.stripTags(TextCrawler.java:261)
                                                                      at com.leocardz.link.preview.library.TextCrawler.access$700(TextCrawler.java:18)
                                                                      at com.leocardz.link.preview.library.TextCrawler$GetCode.doInBackground(TextCrawler.java:147)
                                                                      at com.leocardz.link.preview.library.TextCrawler$GetCode.doInBackground(TextCrawler.java:43)
                                                                      at android.os.AsyncTask$2.call(AsyncTask.java:288)
                                                                      at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                      at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231) 
                                                                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                      at java.lang.Thread.run(Thread.java:841) E/UncaughtException: java.lang.RuntimeException: An error occured while executing doInBackground()
                                                                      at android.os.AsyncTask$3.done(AsyncTask.java:300)
                                                                      at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
                                                                      at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
                                                                      at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                      at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
                                                                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                      at java.lang.Thread.run(Thread.java:841)
                                                                   Caused by: java.lang.VerifyError: org/jsoup/parser/HtmlTreeBuilderState$7
                                                                      at org.jsoup.parser.HtmlTreeBuilderState.<clinit>(HtmlTreeBuilderState.java:245)
                                                                      at E/UncaughtException: java.lang.RuntimeException: An error occured while executing doInBackground()
                                                                      at android.os.AsyncTask$3.done(AsyncTask.java:300)
                                                                      at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
                                                                      at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
                                                                      at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                      at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
                                                                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                      at java.lang.Thread.run(Thread.java:841)
                                                                   Caused by: java.lang.VerifyError: org/jsoup/parser/HtmlTreeBuilderState$7
                                                                      at org.jsoup.parser.HtmlTreeBuilderState.<clinit>(HtmlTreeBuilderState.java:245)
                                                                      at org.jsoup.parser.HtmlTreeBuilder.parse(HtmlTreeBuilder.java:54)
                                                                      at org.jsoup.parser.Parser.parse(Parser.java:100)
                                                                      at org.jsoup.Jsoup.parse(Jsoup.java:58)
                                                                      at com.leocardz.link.preview.library.TextCrawler.stripTags(TextCrawler.java:261)
                                                                      at com.leocardz.link.preview.library.TextCrawler.access$700(TextCrawler.java:18)
                                                                      at com.leocardz.link.preview.library.TextCrawler$GetCode.doInBackground(TextCrawler.java:147)
                                                                      at com.leocardz.link.preview.library.TextCrawler$GetCode.doInBackground(TextCrawler.java:43)
                                                                      at android.os.AsyncTask$2.call(AsyncTask.java:288)
                                                                      at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                      at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231) 
                                                                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                      at java.lang.Thread.run(Thread.java:841) org.jsoup.parser.HtmlTreeBuilder.parse(HtmlTreeBuilder.java:54)
                                                                      at org.jsoup.parser.Parser.parse(Parser.java:100)
                                                                      at org.jsoup.Jsoup.parse(Jsoup.java:58)
                                                                      at com.leocardz.link.preview.library.TextCrawler.stripTags(TextCrawler.java:261)
                                                                      at com.leocardz.link.preview.library.TextCrawler.access$700(TextCrawler.java:18)
                                                                      at com.leocardz.link.preview.library.TextCrawler$GetCode.doInBackground(TextCrawler.java:147)
                                                                      at com.leocardz.link.preview.library.TextCrawler$GetCode.doInBackground(TextCrawler.java:43)
                                                                      at android.os.AsyncTask$2.call(AsyncTask.java:288)
                                                                      at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                      at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231) 
                                                                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                      at java.lang.Thread.run(Thread.java:841) va:231)
                                                                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                      at java.lang.Thread.run(Thread.java:841)
                                                                   Caused by: java.lang.VerifyError: org/jsoup/parser/HtmlTreeBuilderState$7
                                                                      at org.jsoup.paE/UncaughtException: java.lang.RuntimeException: An error occured while executing doInBackground()
                                                                      at android.os.AsyncTask$3.done(AsyncTask.java:300)
                                                                      at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
                                                                      at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
                                                                      at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                      at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
                                                                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                      at java.lang.Thread.run(Thread.java:841)
                                                                   Caused by: java.lang.VerifyError: org/jsoup/parser/HtmlTreeBuilderState$7
                                                                      at org.jsoup.parser.HtmlTreeBuilderState.<clinit>(HtmlTreeBuilderState.java:245)
                                                                      at org.jsoup.parser.HtmlTreeBuilder.parse(HtmlTreeBuilder.java:54)
                                                                      at org.jsoup.parser.Parser.parse(Parser.java:100)
                                                                      at org.jsoup.Jsoup.parse(Jsoup.java:58)
                                                                      at com.leocardz.link.preview.library.TextCrawler.stripTags(TextCrawler.java:261)
                                                                      at com.leocardz.link.preview.library.TextCrawler.access$700(TextCrawler.java:18)
                                                                      at com.leocardz.link.preview.library.TextCrawler$GetCode.doInBackground(TextCrawler.java:147)
                                                                      at com.leocardz.link.preview.library.TextCrawler$GetCode.doInBackground(TextCrawler.java:43)
                                                                      at android.os.AsyncTask$2.call(AsyncTask.java:288)
                                                                      at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                      at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231) 
                                                                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                      at java.lang.Thread.run(Thread.java:841) rser.HtmlTreeBuilderState.<clinit>(HtmlTreeBuilderState.java:245)
                                                                      at org.jsoup.parser.HtmlTreeBuilder.parse(HtmlTreeBuilder.java:54)
                                                                      at org.jsoup.parser.Parser.parse(Parser.java:100)
                                                                      at org.jsoup.Jsoup.parse(Jsoup.java:58)
                                                                      at com.leocardz.link.preview.library.TextCrawler.stripTags(TextCrawler.java:261)
                                                                      at com.leocardz.link.preview.library.TextCrawler.access$700(TextCrawler.java:18)
                                                                      at com.leocardz.link.preview.library.TextCrawler$GetCode.doInBackground(TextCrawler.java:147)
                                                                      at com.leocardz.link.preview.library.TextCrawler$GetCode.doInBackground(TextCrawler.java:43)
                                                                      at android.os.AsyncTask$2.call(AsyncTask.java:288)
                                                                      at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                      at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231) 
                                                                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                      at java.lang.Thread.run(Thread.java:841) E/UncaughtException: java.lang.RuntimeException: An error occured while executing doInBackground()
                                                                      at android.os.AsyncTask$3.done(AsyncTask.java:300)
                                                                      at java.util.concurrent.FutureTask.finisE/UncaughtException: java.lang.RuntimeException: An error occured while executing doInBackground()
                                                                      at android.os.AsyncTask$3.done(AsyncTask.java:300)
                                                                      at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
                                                                      at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
                                                                      at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                      at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
                                                                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                      at java.lang.Thread.run(Thread.java:841)
                                                                   Caused by: java.lang.VerifyError: org/jsoup/parser/HtmlTreeBuilderState$7
                                                                      at org.jsoup.parser.HtmlTreeBuilderState.<clinit>(HtmlTreeBuilderState.java:245)
                                                                      at org.jsoup.parser.HtmlTreeBuilder.parse(HtmlTreeBuilder.java:54)
                                                                      at org.jsoup.parser.Parser.parse(Parser.java:100)
                                                                      at org.jsoup.Jsoup.parse(Jsoup.java:58)
                                                                      at com.leocardz.link.preview.library.TextCrawler.stripTags(TextCrawler.java:261)
                                                                      at com.leocardz.link.preview.library.TextCrawler.access$700(TextCrawler.java:18)
                                                                      at com.leocardz.link.preview.library.TextCrawler$GetCode.doInBackground(TextCrawler.java:147)
                                                                      at com.leocardz.link.preview.library.TextCrawler$GetCode.doInBackground(TextCrawler.java:43)
                                                                      at android.os.AsyncTask$2.call(AsyncTask.java:288)
                                                                      at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                      at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231) 
                                                                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                      at java.lang.Thread.run(Thread.java:841) hCompletion(FutureTask.java:355)
                                                                      at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
                                                                      at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                      at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
                                                                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                      at java.lang.Thread.run(Thread.java:841)
                                                                   Caused by: java.lang.VerifyError: org/jsoup/parser/HtmlTreeBuilderState$7
                                                                      at org.jsoup.parser.HtmlTreeBuilderState.<clinit>(HtmlTreeBuilderState.java:245)
                                                                      at org.jsoup.parser.HtmlTreeBuilder.parse(HtmlTreeBuilder.java:54)
                                                                      at org.jsoup.parser.Parser.parse(Parser.java:100)
                                                                      at org.jsoup.Jsoup.parse(Jsoup.java:58)
                                                                      at com.leocardz.link.preview.library.TextCrawler.stripTags(TextCrawler.java:261)
                                                                      at com.leocardz.link.preview.library.TextCrawler.access$700(TextCrawler.java:18)
                                                                      at com.leocardz.link.preview.library.TextCrawler$GetCode.doInBackground(TextCrawler.java:147)
                                                                      at com.leocardz.link.preview.library.TextCrawler$GetCode.doInBackground(TextCrawler.java:43)
                                                                      at android.os.AsyncTask$2.call(AsyncTask.java:288)
                                                                      at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                      at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231) 
                                                                      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                      at java.lang.Thread.run(Thread.java:841) 

How to proceed with this issue?

**Comment by jdonmoyer** [comment]
It's possible that the PR (https://github.com/LeonardoCardoso/Android-Link-Preview/pull/22) that I just pushed may address this issue.

**Comment by LeonardoCardoso** [comment]
Merged. Can you test it @BharathirajaPerumal and let us know so I can close this issue?
